# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uucZe4W8bGZ46xSv441RQcb4ZVsst7Wx
"""

import os
import json

TELEGRAM_TOKEN = os.environ["TELEGRAM_TOKEN"]
TELEGRAM_CHAT_ID = os.environ["TELEGRAM_CHAT_ID"]

GOOGLE_SHEET_NAME = "Stock_Trigger_Tracker"

# Load Google credentials from GitHub secret
GOOGLE_CREDS = json.loads(os.environ["GOOGLE_CREDENTIALS"])