# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khDjo0tIysUV-c4M7GHrZMRnMPTuw47B
"""

import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime
from telegram_utils import send_telegram_alert
from sheets_utils import connect_sheet, get_sheet_df, append_row

# -------- LOAD NIFTY 500 ----------
symbols = pd.read_csv("nifty500.csv")["Symbol"].tolist()

# -------- CRITERIA FUNCTION ----------
def check_criteria(df):
    df["EMA200"] = df["Close"].ewm(span=200).mean()
    df["Vol_Avg20"] = df["Volume"].rolling(20).mean()

    latest = df.iloc[-1]
    prev = df.iloc[-2]

    cond1 = (latest["Close"] - prev["Close"]) / prev["Close"] >= 0.05
    cond2 = latest["Volume"] > latest["Vol_Avg20"]
    cond3 = latest["Close"] > latest["EMA200"]

    return cond1 and cond2 and cond3

# -------- RETURN CALC ----------
def calculate_return(entry_price, future_price):
    return round((future_price - entry_price) / entry_price * 100, 2)

# -------- SCANNER ----------
def scan_market(sheet, existing_df):

    today = datetime.today().date()

    triggered_today = []

    for ticker in symbols:
        try:
            df = yf.download(ticker, period="1y", interval="1d", progress=False)
            df.dropna(inplace=True)

            if len(df) < 220:
                continue

            if check_criteria(df):

                if ticker in existing_df["Ticker"].values:
                    continue

                trigger_price = df["Close"].iloc[-1]

                append_row(sheet, [
                    ticker,
                    str(today),
                    trigger_price,
                    "", "", "", "",
                    "ACTIVE",
                    str(today)
                ])

                triggered_today.append(ticker)

        except:
            continue

    if triggered_today:
        msg = f"🚨 Nifty500 Breakout Alerts 🚨\n\n" + "\n".join(triggered_today)
        send_telegram_alert(msg)

# -------- TRACKER ----------
def update_tracker(sheet, df_sheet):

    today = datetime.today().date()

    for idx, row in df_sheet.iterrows():

        if row["Status"] != "ACTIVE":
            continue

        ticker = row["Ticker"]
        trigger_date = pd.to_datetime(row["Trigger Date"])
        entry_price = row["Trigger Price"]

        df = yf.download(ticker, period="6mo", interval="1d", progress=False)
        df.dropna(inplace=True)

        trading_days = df[df.index >= trigger_date]

        if len(trading_days) == 0:
            continue

        latest_price = trading_days["Close"].iloc[-1]

        returns = {}

        periods = {5: "D+5 Return", 10: "D+10 Return",
                   20: "D+20 Return", 60: "D+60 Return"}

        for p, col in periods.items():
            if len(trading_days) >= p:
                future_price = trading_days["Close"].iloc[p-1]
                returns[col] = calculate_return(entry_price, future_price)

        # Update cells
        for col, val in returns.items():
            col_index = df_sheet.columns.get_loc(col) + 1
            sheet.update_cell(idx+2, col_index, val)

        if len(trading_days) >= 60:
            status_col = df_sheet.columns.get_loc("Status") + 1
            sheet.update_cell(idx+2, status_col, "COMPLETED")

# -------- MAIN ----------
if __name__ == "__main__":

    sheet = connect_sheet()

    try:
        df_sheet = get_sheet_df(sheet)
    except:
        # First run header
        sheet.append_row([
            "Ticker", "Trigger Date", "Trigger Price",
            "D+5 Return", "D+10 Return",
            "D+20 Return", "D+60 Return",
            "Status", "Last Updated"
        ])
        df_sheet = get_sheet_df(sheet)

    scan_market(sheet, df_sheet)
    df_sheet = get_sheet_df(sheet)
    update_tracker(sheet, df_sheet)
