# -*- coding: utf-8 -*-
"""sheets_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4QUc_0kpTFeaEL7mJcDgc4_HOFQWVk8
"""

import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
from config import GOOGLE_CREDS, GOOGLE_SHEET_NAME

def connect_sheet():
    scope = [
        "https://spreadsheets.google.com/feeds",
        "https://www.googleapis.com/auth/drive"
    ]
    creds = ServiceAccountCredentials.from_json_keyfile_dict(GOOGLE_CREDS, scope)
    client = gspread.authorize(creds)
    sheet = client.open(GOOGLE_SHEET_NAME).sheet1
    return sheet

def get_sheet_df(sheet):
    data = sheet.get_all_records()
    return pd.DataFrame(data)

def append_row(sheet, row):
    sheet.append_row(row)