# -*- coding: utf-8 -*-
"""telegram_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XHUbqRSwUYJJfaF90C7viZbZnHIfpnS
"""

import requests
from config import TELEGRAM_TOKEN, TELEGRAM_CHAT_ID

def send_telegram_alert(message):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": message
    }
    requests.post(url, data=payload)